# Generated by Django 4.2.4 on 2023-11-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('codBod', models.AutoField(primary_key=True, serialize=False)),
                ('nomBod', models.CharField(max_length=30)),
                ('dirBod', models.CharField(max_length=30)),
                ('cantPas', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificadores',
            fields=[
                ('codCla', models.IntegerField(primary_key=True, serialize=False)),
                ('codBod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='ColorPrincipal',
            fields=[
                ('codCp', models.AutoField(primary_key=True, serialize=False)),
                ('nomCp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ColorSecundario',
            fields=[
                ('codCs', models.AutoField(primary_key=True, serialize=False)),
                ('nomCs', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('codCom', models.IntegerField(primary_key=True, serialize=False)),
                ('nomCom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fardos',
            fields=[
                ('codFar', models.AutoField(primary_key=True, serialize=False)),
                ('exiStF', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('codPt', models.AutoField(primary_key=True, serialize=False)),
                ('nomPt', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('codPer', models.IntegerField(primary_key=True, serialize=False)),
                ('nomPer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recolectores',
            fields=[
                ('codRec', models.AutoField(primary_key=True, serialize=False)),
                ('codBod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='TipoFardo',
            fields=[
                ('codTf', models.AutoField(primary_key=True, serialize=False)),
                ('nomTf', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovFardo',
            fields=[
                ('codMovF', models.AutoField(primary_key=True, serialize=False)),
                ('nomFar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimientoM',
            fields=[
                ('codMovM', models.AutoField(primary_key=True, serialize=False)),
                ('nomMov', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTela',
            fields=[
                ('codTt', models.AutoField(primary_key=True, serialize=False)),
                ('nomTt', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('codTra', models.AutoField(primary_key=True, serialize=False)),
                ('rutTra', models.IntegerField()),
                ('nomTra', models.CharField(max_length=30)),
                ('dirTra', models.CharField(max_length=30)),
                ('telTra', models.CharField(max_length=30)),
                ('emailTra', models.CharField(max_length=30)),
                ('codCom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codUser', models.CharField(max_length=100, unique=True)),
                ('passW', models.CharField(max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('codPer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.perfil')),
                ('codTra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.trabajadores')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('codUbi', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ubiStat', models.BooleanField()),
                ('stock', models.IntegerField()),
                ('codBod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('codTela', models.AutoField(primary_key=True, serialize=False)),
                ('exiSt', models.BooleanField()),
                ('codCla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.clasificadores')),
                ('codCp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.colorprincipal')),
                ('codCs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.colorsecundario')),
                ('codPt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.patron')),
                ('codTt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.tipotela')),
            ],
        ),
        migrations.CreateModel(
            name='RegBodegaMuestra',
            fields=[
                ('codRegM', models.AutoField(primary_key=True, serialize=False)),
                ('fechaIngM', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('codMovM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.tipomovimientom')),
                ('codTela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.tela')),
                ('codUbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='RegBodegaFardo',
            fields=[
                ('codRegF', models.AutoField(primary_key=True, serialize=False)),
                ('fechaIngFar', models.DateField()),
                ('codBode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.bodega')),
                ('codFar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.fardos')),
                ('codMovF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.tipomovfardo')),
                ('codRec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.recolectores')),
            ],
        ),
        migrations.AddField(
            model_name='recolectores',
            name='codTra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.trabajadores'),
        ),
        migrations.AddField(
            model_name='fardos',
            name='codRec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.recolectores'),
        ),
        migrations.AddField(
            model_name='fardos',
            name='codTf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.tipofardo'),
        ),
        migrations.AddField(
            model_name='clasificadores',
            name='codTra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.trabajadores'),
        ),
        migrations.CreateModel(
            name='Bodeguero',
            fields=[
                ('codBode', models.AutoField(primary_key=True, serialize=False)),
                ('codBod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.bodega')),
                ('codTra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.trabajadores')),
            ],
        ),
        migrations.AddField(
            model_name='bodega',
            name='codCom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.comuna'),
        ),
        migrations.CreateModel(
            name='Artesano',
            fields=[
                ('codArt', models.AutoField(primary_key=True, serialize=False)),
                ('codBod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.bodega')),
                ('codTra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.trabajadores')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('codAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('codBod', models.IntegerField()),
                ('codTra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBDcrud.trabajadores')),
            ],
        ),
    ]
